spring.application.name=backend
server.port=8080

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gigshield_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:Kuberan@2006}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:gigshield-super-secret-jwt-key-2026-devtrails}
jwt.expiration=86400000

# Trigger Engine URL (your Flask server)
trigger.engine.url=${TRIGGER_ENGINE_URL:http://localhost:5001}

# ML Payout API URL (port 5003)
ml.premium.url=${ML_PREMIUM_URL:http://localhost:5003}